-- Esquema básico para un cotizador en Oracle
-- Crear tablas principales

CREATE TABLE clientes (
  cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(200) NOT NULL,
  correo      VARCHAR2(200),
  telefono    VARCHAR2(50),
  creado_en   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE productos (
  producto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku         VARCHAR2(50) NOT NULL UNIQUE,
  nombre      VARCHAR2(200) NOT NULL,
  precio      NUMBER(12, 2) NOT NULL,
  activo      CHAR(1) DEFAULT 'S' NOT NULL,
  creado_en   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE cotizaciones (
  cotizacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id     NUMBER NOT NULL,
  usuario        VARCHAR2(100) NOT NULL,
  estado         VARCHAR2(20) DEFAULT 'BORRADOR' NOT NULL,
  subtotal       NUMBER(12, 2) DEFAULT 0 NOT NULL,
  impuestos      NUMBER(12, 2) DEFAULT 0 NOT NULL,
  total          NUMBER(12, 2) DEFAULT 0 NOT NULL,
  creado_en      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT cotizaciones_cliente_fk
    FOREIGN KEY (cliente_id)
    REFERENCES clientes (cliente_id)
);

CREATE TABLE cotizacion_detalle (
  detalle_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cotizacion_id  NUMBER NOT NULL,
  producto_id    NUMBER NOT NULL,
  cantidad       NUMBER(12, 2) NOT NULL,
  precio_unitario NUMBER(12, 2) NOT NULL,
  total_linea    NUMBER(12, 2) NOT NULL,
  CONSTRAINT cotizacion_detalle_cotizacion_fk
    FOREIGN KEY (cotizacion_id)
    REFERENCES cotizaciones (cotizacion_id),
  CONSTRAINT cotizacion_detalle_producto_fk
    FOREIGN KEY (producto_id)
    REFERENCES productos (producto_id)
);

-- Tipos para insertar detalle en bloque
CREATE OR REPLACE TYPE t_item_cotizacion AS OBJECT (
  producto_id NUMBER,
  cantidad    NUMBER
);
/

CREATE OR REPLACE TYPE t_items_cotizacion AS TABLE OF t_item_cotizacion;
/

-- Paquete para crear cotizaciones
CREATE OR REPLACE PACKAGE cotizador_pkg AS
  PROCEDURE crear_cotizacion(
    p_cliente_id   IN clientes.cliente_id%TYPE,
    p_usuario      IN cotizaciones.usuario%TYPE,
    p_items        IN t_items_cotizacion,
    p_tasa_impuesto IN NUMBER DEFAULT 0.16,
    p_cotizacion_id OUT cotizaciones.cotizacion_id%TYPE
  );
END cotizador_pkg;
/

CREATE OR REPLACE PACKAGE BODY cotizador_pkg AS
  PROCEDURE crear_cotizacion(
    p_cliente_id   IN clientes.cliente_id%TYPE,
    p_usuario      IN cotizaciones.usuario%TYPE,
    p_items        IN t_items_cotizacion,
    p_tasa_impuesto IN NUMBER DEFAULT 0.16,
    p_cotizacion_id OUT cotizaciones.cotizacion_id%TYPE
  ) IS
    v_subtotal NUMBER(12, 2) := 0;
    v_impuestos NUMBER(12, 2) := 0;
    v_total NUMBER(12, 2) := 0;
  BEGIN
    INSERT INTO cotizaciones (cliente_id, usuario)
    VALUES (p_cliente_id, p_usuario)
    RETURNING cotizacion_id INTO p_cotizacion_id;

    FOR i IN 1 .. p_items.COUNT LOOP
      DECLARE
        v_precio productos.precio%TYPE;
        v_total_linea NUMBER(12, 2);
      BEGIN
        SELECT precio
          INTO v_precio
          FROM productos
         WHERE producto_id = p_items(i).producto_id
           AND activo = 'S';

        v_total_linea := v_precio * p_items(i).cantidad;
        v_subtotal := v_subtotal + v_total_linea;

        INSERT INTO cotizacion_detalle (
          cotizacion_id,
          producto_id,
          cantidad,
          precio_unitario,
          total_linea
        ) VALUES (
          p_cotizacion_id,
          p_items(i).producto_id,
          p_items(i).cantidad,
          v_precio,
          v_total_linea
        );
      END;
    END LOOP;

    v_impuestos := ROUND(v_subtotal * p_tasa_impuesto, 2);
    v_total := v_subtotal + v_impuestos;

    UPDATE cotizaciones
       SET subtotal = v_subtotal,
           impuestos = v_impuestos,
           total = v_total,
           estado = 'GENERADA'
     WHERE cotizacion_id = p_cotizacion_id;
  END crear_cotizacion;
END cotizador_pkg;
/
